# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Timezone
timezone: Europe/Stockholm

# Site Metadata
title: "Jaison Jeevan Sequeira"
tagline: "Population Genetics & Computational Biology"
description: "Personal website and academic portfolio of Dr. Jaison Jeevan Sequeira, Postdoctoral Fellow at Uppsala University researching population genetics, ancient DNA, and South Asian demographic history."

# Fill in the protocol & hostname for your site.
url: "https://jaisonjseq.github.io"

github:
  username: jaisonjseq

twitter:
  username: jaisonjseq

social:
  name: "Jaison Jeevan Sequeira"
  email: "jaisonjseq@gmail.com"
  links:
    - https://twitter.com/jaisonjseq
    - https://github.com/jaisonjseq
    - https://orcid.org/0000-0001-6859-9978
    - https://sites.google.com/view/jaison-popgen
    - https://popgenworld.blogspot.com/

# Site Verification Settings
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics Settings
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views settings
pageviews:
  provider:

# Prefer color scheme setting.
theme_mode:

# The CDN endpoint for media resources.
cdn:

# Avatar image in sidebar
avatar: /assets/img/profile.jpg

# The URL of the site-wide social preview image
social_preview_image:

# Global switch for TOC in posts.
toc: true

actions:
  edit_post:
    enabled: false
    url: ""
    static_url: false

comments:
  provider:

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true

paginate: 10
baseurl: ""

# ------------ System Defaults ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
